### ISSUE TITLE
Dictionaries incorrectly translated to CL

### ISSUE THREAD

**Issue by rpgoldman** [digikar99/py4cl2#11]
I have an object with a property that is a dictionary whose keys are Python tuples.

When I try to lookup an entry in this table, py4cl2 tries to send the table over to lisp and reconstruct it as hash table.  This doesn't work, because it tries to make the keys in a naive way, yielding errors like this:

```
in: LET ((TABLE (MAKE-HASH-TABLE :TEST 'EQUAL)))
;     (":aCapitolCity" ":label")
; 
; caught ERROR:
;   illegal function call

;     (":aCapitolCity" ":country")
```

Those keys need to be quoted in the translation, but are not.

One can easily work around this, but it's definitely a bug.

To be honest, I'm a little surprised that py4cl2 translates the dictionary instead of just giving me a handle on it, and letting me reference it.

**Comment by digikar99** [comment]
> just giving me a handle on it, and letting me reference it

You can use `py4cl2:with-remote-objects(*)` (`py4cl:remote-objects(*)`)
