### ISSUE TITLE
Python error: __init__() missing  XX required positional

### ISSUE THREAD

**Issue by DurhamSmith** [digikar99/py4cl2#14]
Hello,

I am currently trying to use py4cl2 to use the [meep](https://github.com/NanoComp/meep) and [mpb](https://github.com/NanoComp/mpb) libraries. 

I however run into some issues when trying to create classes. For example when I try to create a [ModeSolver](https://github.com/NanoComp/meep/blob/cdae1a830fd5e25b359a64676317d63e6a59f390/python/solver.py#L72)
 
If I run `(pyeval "mpb.ModeSolver()")` I get the correct result
```
#S(PY4CL2::PYTHON-OBJECT
   :TYPE "<class 'meep.mpb.solver.ModeSolver'>"
   :HANDLE 773)
```

However if I try to run 
```
(defpymodule "meep.mpb" t :lisp-package "MPB")
(MPB:mode-solver/class)
```
I get
```
Python error: __init__() missing 20 required positional arguments: 'num_bands', 'resolution', 'lat', 'tolerance', 'mesh_size', '_default_material', 'deterministic', 'target_freq', 'dims', 'verbose', 'periodicity', 'flops', 'negative_epsilon_ok', 'epsilon_input_file', 'mu_input_file', 'force_mu', 'use_simple_preconditioner', 'grid_size', 'eigensolver_nwork', and 'eigensolver_block_size'
```

Furthermore if I try to provide some of these args I get the following

```
(mpb:mode-solver/class
                     :geometry_lattice (meep:lattice/class :size '(1 1 1)))
```
I get

```
Python error: __init__() got an unexpected keyword argument 'geometry_lattice'
```

I am not sure if I am calling the constructor correctly (for py4cl2).[ It seems these lines might also play a roll](https://github.com/NanoComp/meep/blob/cdae1a830fd5e25b359a64676317d63e6a59f390/python/solver.py#L130). I will investigate deeper and add to this but any help or usage clarification would be greatly appreciate.

**Comment by digikar99** [comment]
`(describe 'mpb:mode-solver/class)` or SLIME's `C-c C-d d` aka `slime-describe-symbol` yields:

```lisp
MPB:MODE-SOLVER/CLASS
  [symbol]

MODE-SOLVER/CLASS names a compiled function:
  Lambda-list: (&REST ARGS)
  Derived type: FUNCTION
  Documentation:
    None
  Source form:
    (LAMBDA (&REST PY4CL2::ARGS)
      "None"
      (BLOCK MPB:MODE-SOLVER/CLASS
        NIL
        (RAW-PYEXEC "import meep.mpb as mpb")
        (APPLY #'PYCALL "mpb.mode_solver" PY4CL2::ARGS)))
```

So, this is actually calling `mpb.mode_solver` rather than the expected `mpb.ModeSolver`; and `mpb.mode_solver()` does yield an error in python as well, while `mpb.ModeSolver()` does not. I lack any experience to comment on this aspect, if this is pythonic, or if this should be handled better by lisp*.

*Raise a condition on name collision, and/or provide options with use with `(named-readtables:in-readtable :modern)` and/or inverted case, though this also requires support from SLIME.

**Comment by DurhamSmith** [comment]
Thanks, I have managed to work around this by creating a `ModeSolver` then assigning the slots.

**Comment by digikar99** [comment]
Perhaps the simplest no-fix method for the moment could be to call `(pycall "meep.mpb.ModeSolver" ...)`.
