### ISSUE TITLE
Python processes keep dying.

### ISSUE THREAD

**Issue by DurhamSmith** [digikar99/py4cl2#15]
Hello, I am currently trying to use py4cl2 to use the meep and mpb libraries.

I have a working python script that I would like to port to cl using py4cl2.

The CL code is [here](https://pastebin.com/7pdjKP13) and the corresponding python script is [here](https://pastebin.com/MYUFJzJj)

The python script runs fine, but once I try to `run_tm` (line 62 in python, line 111 in CL) I run into the following error:
```
The python process
  #<UIOP/LAUNCH-PROGRAM::PROCESS-INFO {1004AE6543}>
has died. Unable to read (or write) from it
```

Could you perhaps provide some information on what could be causing this, how to avoid it, and how to better solve/trace bugs/undesired behavior in py4cl2?

**Comment by digikar99** [comment]
Assuming you do make some minor changes to the script and are able to run it, along with some other output, I do get the following outside the debugger:

```
Initializing eigensolver data
Computing 8 bands with 1e-07 tolerance
terminate called after throwing an instance of 'std::runtime_error'
  what():  meep: Error: UnknownLispObject is not a valid GeometricObject type

Abort
```

Rerunning in the terminal yielded some more lines

```
Aborted (core dumped)
Unhandled SIMPLE-ERROR in thread #<SB-THREAD:THREAD "main thread" RUNNING
                                    {101AFF01E3}>:
  Unbound condition slot: STREAM
```

I hope to look into if this output can be made available in the debugger to make it more informative.

**Comment by DurhamSmith** [comment]
Ok, I found the issue and fixed it, although im running into new errors now.
Where can I find the information like;
```
Initializing eigensolver data
Computing 8 bands with 1e-07 tolerance
terminate called after throwing an instance of 'std::runtime_error'
  what():  meep: Error: UnknownLispObject is not a valid GeometricObject type

Abort
```
when I have failing code.

**Comment by DurhamSmith** [comment]
I fixed some errors and restarted emacs/sly/sbcl
When I try to run the working code I see that messages similar to the one you gave are now printed to my repl. For some reason it was not doing this before. Is this where you got that debug information or is there a better way to go about finding errors when using `py4cl2`?

**Comment by digikar99** [comment]
Yes the errors were printed at the REPL - in stdout - instead of the debugger. There isn't a better way to debug at the moment.

The core-dumped; that arises because the python functions are expecting a GeometricObject while the lisp code is sending lisp objects that aren't being converted to python objects. In `(setq ms ...)`you have defined `mds` but haven't quite put it to use, in addition:

```lisp
PCA> (pyslot-value ms 'geometry)
#(#<DIELECTRIC {102B337F63}> #<DIELECTRIC {102B337FB3}>
  #<DIELECTRIC {102B338003}> #<DIELECTRIC {102B338053}>
  #<DIELECTRIC {102B3380A3}> #<DIELECTRIC {102B3380F3}>
  #<DIELECTRIC {102B338143}> #<DIELECTRIC {102B338193}>)
```

**Comment by digikar99** [comment]
It seems you intended to do:

```lisp
         (mds (mapcar #'(lambda (d)
                          (mp-dielectric d))
                      ds))
         (geometry (apply #'vector mds))         
```

instead of:

```lisp
       (geometry (apply #'vector ds))
       (mds (mapcar #'(lambda (d)
                        (mp-dielectric d))
                    ds))
```

Post this the iterations do run, but there are other errors:

```
.
.
.
    iteration   20: trace = 1.753720570143875 (3.23738e-06% change)
Finished solving for bands 2 to 8 after 20 iterations.
zoddfreqs:, 1, 0, 0, 0, 0, 0, 0.395408, 0.463052, 0.463197, 0.483326, 0.48351, 0.591944, 0.592132
elapsed time for k point: 2.754639148712158
Unhandled PYERROR in thread #<SB-THREAD:THREAD "main thread" RUNNING
                               {101AFF01E3}>:
  Python error: 'vector3' object has no attribute 'close'

```

**Comment by digikar99** [comment]
And this (again) is because `meep:vector-3/class` is actually calling `meep.vector3` instead of `meep.Vector3`.

The other thing to take care of is the meep expects `Vector3` objects at various places rather than python tuples (equivalent to lisp lists). So 

- `(apply #'pycall "meep.Vector3" size)` instead of just `size`
- `(apply #'pycall "meep.Vector3" center)` instead of just `center` 
- and `(pycall "meep.Vector3" (/ -1 3) (/ 1 3))` instead of just `(list (/ -1 3) (/ 1 3))`

So, another point of note for me: customizable pythonizers will be useful (another user had suggested about them [here](https://github.com/bendudson/py4cl/issues/48)).

**Comment by DurhamSmith** [comment]
Thanks, I managed to identify and solve those issues quickly when I was getting the errors printed  to stdout. I wonder why it wasn't initially doing this but after a restart it did and I havn't been able to recreate the lack of output to stdout.

I managed to fix mine by replacing;

```
(defun meep-v3 (&optional x y z)
  (let ((v3 (meep:vector-3/class)))
    (setf (pyslot-value v3 'x) (when x (coerce x 'double-float)))
    (setf (pyslot-value v3 'y) (when y (coerce y 'double-float)))
    (setf (pyslot-value v3 'z) (when z (coerce z 'double-float)))
    v3))
```

with 
```
(defun meep-v3 (&optional (x 0d0) (y 0d0) (z 0d0))
    (pyeval "meep.Vector3(" x "," y "," z ")"))
```
and actually calling `mp-dielectric`

And yes, the problem with `meep:vector-3/class` is we get a `meep.vector3` whereas `(pyeval "meep.Vector3(1,2,3)")` gives a `meep.geom.Vector3`.
