### ISSUE TITLE
Example code of chain can't run

### ISSUE THREAD

**Issue by qishi-hep** [digikar99/py4cl2#16]
Hi, 

The following example code in doc doesn't work (I have changed the "py4cl" to "py4cl2").

https://github.com/digikar99/py4cl2/blob/5078ec2a37dbdd0e0d40ec352736d5b47ccddc22/docs/index.md?plain=1#L725-L731

Other functions work fine, so I think the `chain` in py4cl2 may not support that feature.

-----------------------------
Error information:

; in: LET ((FORMAT-STR "hello {0}") (ARGUMENT "world"))
;     (LET ((FORMAT-STR "hello {0}") (ARGUMENT "world"))
;       (PY4CL2:CHAIN FORMAT-STR (FORMAT ARGUMENT)))
; 
; caught STYLE-WARNING:
;   The variable FORMAT-STR is defined but never used.
; 
; caught STYLE-WARNING:
;   The variable ARGUMENT is defined but never used.
; 
; compilation unit finished
;   caught 2 STYLE-WARNING conditions

Python error: Traceback (most recent call last):
  File "/dev/fd/63", line 407, in message_dispatch_loop
  File "<string>", line 1, in <module>
NameError: name 'format_str' is not defined
   [Condition of type PY4CL2:PYERROR]

**Comment by digikar99** [comment]
Here, this particular example code is incorrect; the correct code is given slightly below:

```lisp
CL-USER> (let ((format-str "hello {0}")
               (argument "world"))
           (chain* format-str `(format ,argument)))
"hello world"
```

This change of `chain(*)` to a more "uniform" format is one of the changes from py4cl to py4cl2. One reason for this is to make it more similar to [parenscript's version of chain](https://parenscript.common-lisp.dev/reference.html), and the other, if I recall correctly, is that `py4cl:chain` doesn't allow method names to be supplied through a lisp variable (Correct me if I'm missing something!). 

I'll update the documentation, thanks for pointing out!

**Comment by qishi-hep** [comment]
I got it. Thanks. 👍
