### ISSUE TITLE
python-process-startup-error when calling seemingly any function

### ISSUE THREAD

**Issue by IAmRasputin** [digikar99/py4cl2#18]
_For reference, attempting to run this on an M1 arm64 MacBook, with an activated conda environment._

Whenever I call a `py4cl2` function in the REPL (I've been using `pyversion-info` to reproduce), it signals a condition, and dumps the following error to output:

```
Unable to start python process "~/miniconda3/envs/science/bin/python"

 Error: 

bash: bad substitution: no closing `)' in <(cat <<"EOF"

...

[ THE ENTIRE CONTENTS OF py4cl.py ]

...

EOF
)
cat: stdout: Broken pipe
   [Condition of type PYTHON-PROCESS-STARTUP-ERROR]
```

Happy to provide more machine info/context.

**Comment by digikar99** [comment]
Is bash version up-to-date? On linux, I have:

```bash
$ ~ bash --version
GNU bash, version 4.4.20(1)-release (x86_64-pc-linux-gnu)
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
```

**Comment by IAmRasputin** [comment]
Oh!  That does seem to be the issue; I'm still running bash 3.2 on my end, which this parser bug seems to affect.

I think, since `zsh` is now the default shell on MacOS, it never occurred to me to install an updated version of `bash`.

Thanks!
