### ISSUE TITLE
Non-uniform behavior of `#'pyeval`

### ISSUE THREAD

**Issue by jcguu95** [digikar99/py4cl2#19]
While `(pyeval "1+1")` returns the lisp integer `2`, `(pyeval "1")` returns the lisp string `"1"`. 

Is this a feature (or a bug)?

**Comment by jcguu95** [comment]
Also, the following should return `NIL`, but it returns the lisp string `"None"`.

```
(pyexec "import time")
(pyeval "time.sleep(1)")
```

**Comment by digikar99** [comment]
> While `(pyeval "1+1")` returns the lisp integer `2`, `(pyeval "1")` returns the lisp string `"1"`.
> 
> Is this a feature (or a bug)?

I have felt 1 as the more appropriate output for `(pyeval 1)`, and `"1"` as the more appropriate output for `(pyeval "1")`.

> Also, the following should return `NIL`, but it returns the lisp string `"None"`.
> 
> ```
> (pyexec "import time")
> (pyeval "time.sleep(1)")
> ;; => "None"
> ```
 
py4cl2 follows this [default mapping](https://digikar99.github.io/py4cl2/#type-mapping-and-pythonize):

```
nil    False
t      True
"None" None
"()"   () # empty tuple
```

You can [customize it](https://digikar99.github.io/py4cl2/#customizing-type-mapping) though!

**Comment by jcguu95** [comment]
Ultimately, python needs to evaluate some string `str`. Is there a lisp function `#'py-evaluate-raw` that does this with `(py-evaluate-raw str)`?

**Comment by digikar99** [comment]
Yes, there's [raw-pyeval and raw-pyexec](https://digikar99.github.io/py4cl2/#doing-arbitrary-things-in-python)!

**Comment by jcguu95** [comment]
Is it safe to say that all messages from Lisp to python has to go through `raw-py` at the end (i.e. `raw-py` is the ultimate entry to the python world)?

**Comment by digikar99** [comment]
At this point, `raw-py` seems to be a result of incomplete refactor/cleanup while I was working on py4cl2 from py4cl. `raw-py` handles the message types `e` and `x`, but there are other message types as can be seen in the `message_dispatch_loop` in py4cl.py.
