### ISSUE TITLE
Problem with getting it to work

### ISSUE THREAD

**Issue by qubit55** [digikar99/py4cl2#29]
Hello, after installing py4cl2 and running:

`(pyversion-info)`

I'm getting:

File "/dev/fd/63", line 214
    infnan = "infd0" : "float-features:double-float-positive-infinity"
                     ^
SyntaxError: invalid syntax

**Comment by digikar99** [comment]
Could you provide more details about your system?

- OS
- bash version
- Value of `py4cl2:*config*` - or equivalently `(py4cl2:config-var 'py4cl2:pycmd)`
- python version

**Comment by qubit55** [comment]
Sure:

* macOS, 11.7.10
* zsh 5.8 (x86_64-apple-darwin20.0)
* /Users/<user-name>/opt/anaconda3/bin/python
* Python 3.9.13

**Comment by digikar99** [comment]
> zsh 5.8 (x86_64-apple-darwin20.0)

Can you specifically report the bash version via `bash --version`? [If it's as old as 3.2, try updating it to a more recent bash.](https://stackoverflow.com/questions/32481734/shell-error-with-bash-bad-substitution-no-closing)

**Comment by qubit55** [comment]
Yep, here you go:

GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin20)

Ok, I see, so I need to update it then.

**Comment by qubit55** [comment]
Ok, after updating bash everything is working now, thanks a lot for your help! :)  

Maybe, it's worth adding this corner-case to the readme? Let me know the best place to add to and I can do it.

**Comment by digikar99** [comment]
Okay, great!

It's actually a part of the [Highlights and Limitations](https://digikar99.github.io/py4cl2/#highlights-and-limitations-of-py4cl), but may be it could be made more prominent by making a specific section for MacOS users.

**Comment by qubit55** [comment]
Oh, my bad, I should've noticed it. I guess, wouldn't hurt to add a section indeed.

**Comment by digikar99** [comment]
I have merged https://github.com/digikar99/py4cl2/pull/30. Thanks!

**Comment by qubit55** [comment]
Awesome, thanks!
