### ISSUE TITLE
Some systems failed to build for Quicklisp dist

### ISSUE THREAD

**Issue by quicklisp** [digikar99/py4cl2#5]
Building with SBCL 2.0.6 / ASDF 3.3.1 for quicklisp dist creation.

Commit id e78e35d74b38b0a7a8bbafe059754b76bda10eaa

*py4cl2/tests* fails to build with the following error:

```
; caught ERROR:
;   (during macroexpansion of (PY4CL2:DEFPYMODULE "networkx" ...))
;   Python error: No module named 'networkx'
...
Unhandled UIOP/LISP-BUILD:COMPILE-FILE-ERROR in thread #<SB-THREAD:THREAD "main thread" RUNNING {1000A30083}>: COMPILE-FILE-ERROR while compiling #<CL-SOURCE-FILE "py4cl2/tests" "package">

```

[Full log here](http://report.quicklisp.org/2020-10-15/failure-report/py4cl2.html)

**Comment by digikar99** [comment]
Two things

1. Does `quicklisp` test loadability of the test-systems?
2. This is being fetched from the Releases, right? Because the part on `networkx` is unreleased as of yet.

**Comment by quicklisp** [comment]
I test all systems in a project.

I am currently set up to pull the latest commits for py4cl2. I can change
it to using the latest github release if that's what you prefer.

**Comment by digikar99** [comment]
>I test all systems in a project.

I see. I'm likely to add more python code / libraries for regression tests in the future. Another way I could go about it while not making quicklisp break is testing these only if `#+travis` - I already do do that for some tests. And add instructions for testing when users want to test `py4cl2` on their systems. Is that within the philosophy of quicklisp? (So, quicklisp will work as it is; users can test the systems; but a few tweaks and more installations would be necessary for the more rigorous tests.)

>I can change it to using the latest github release if that's what you prefer.

Please do so.

PS: At some time in the future, perhaps, lispers can set up a site that has the configuration options for `quicklisp` concerning things like the location to fetch from.

**Comment by quicklisp** [comment]
> Is that within the philosophy of quicklisp?

In general Quicklisp's dist construction does not really fit in with a notion of "system definition is included with a project but not available to load by default" - the availability is statically determined up front, and the available systems are presented in a static index.

I'm not sure of the best way to achieve something like that. I think it might work to define extended tests in a separate repo and clone them into local-projects (or any other ASDF-visible place) for users who want to perform extended tests. But that also means separating them from the main repo, which isn't ideal either. Another option might be to instruct users to do something like `(push (asdf:system-relative-pathname "py4cl2" #p"tests/extended/") asdf:*central-registry*)`, which is a little cumbersome but would allow you to keep things together in one repo.

Hope this helps - I am happy to explain more about quicklisp if needed.

**Comment by digikar99** [comment]
Okay, the testing process is already a fair bit complex, since some things (especially locks and threading it seems) some times fail on travis. So, adding this as well would be less complex than the other options I think.

I'll keep this open - ensuring this is fixed requires v2.5.0 to be in quicklisp.

**Comment by digikar99** [comment]
The fact that `py4cl2/tests` is currently building on quicklisp seems to indicate that quicklisp build server (is that the correct term?) has numpy installed. That numpy would be installed shouldn't be assumed, right?

**Comment by quicklisp** [comment]
For building systems, I install dependencies like that if I know about them.

**Comment by digikar99** [comment]
Would it be possible to install `python3-networkx` as well?

**Comment by digikar99** [comment]
Both the need for networkx and numpy, as well as the py4cl2/tests system should be removed from quicklisp from the next release. The tests now rest at https://github.com/digikar99/py4cl2-tests. Thanks for the suggestion!
