### ISSUE TITLE
Problems with python argument list translation

### ISSUE THREAD

**Issue by rpgoldman** [digikar99/py4cl2#9]
When I was using `py4cl` it seemed like python named arguments turned into lisp keyword arguments, at least some of the time.

Now, using `py4cl2` I seem to be getting a mismatch.

Here's a python function header from my program:

```
def pull_registry(
    *,
    auth: Optional[Dict[str, str]] = None,
    root_url: str = "https://foo.project.cloud/api/v4",
    debug: bool = False,
) -> RegistryProxy:
```

I translated this using the following command:

```
(defpymodule "registry_client_wrapper" nil :lisp-package "RC")
```

I would have expected `pull_registry` to be translated to a lisp function with three keyword arguments, but these turn into optional arguments, instead:

```
COMPOSITION-EXAMPLE> (sb-introspect:function-arglist #'rc:pull-registry)
(&OPTIONAL (RC::DEBUG 'NIL) (RC::ROOT-URL "https://foo.project.cloud/api/v4")
 (RC::AUTH "None"))
```

That is not super convenient, but we could deal with it.  However, *invoking* the function this way goes wrong:

```
Python error: pull_registry() takes 0 positional arguments but 3 were given
   [Condition of type PY4CL2:PYERROR]

Restarts:
 0: [RETRY] Retry SLY mREPL evaluation request.
 1: [*ABORT] Return to SLY's top level.
 2: [ABORT] abort thread (#<THREAD "sly-channel-1-mrepl-remote-1" RUNNING {1001A965A3}>)
```

Is it possible that the `*` annotation in the function header is causing the problem?

**Comment by rpgoldman** [comment]
I believe I know why this is happening, or at least part of the picture.  If you look at https://github.com/digikar99/py4cl2/blob/dbbf581077a46368b47c244148742c662cb544c3/src/import-export.lisp#L98 you will see this:

```
(pos-only (find #\/ (pyeval "str(" signature ")")))
```

py4cl2 infers that arguments are positional only if it finds a "/" character somewhere in the signature of the function (represented as a string).

This is *definitely* wrong -- if you look at the signature of my function:

```
<Signature (*, auth: Union[Dict[str, str], NoneType] = None, root_url: str = 'https://foo.project.cloud/api/v4', debug: bool = False) -> registry_client_wrapper.wrapper.RegistryProxy>
```

py4cl2 sees the slash in the default value of my parameter and decides that all of the arguments are positional only (precisely the opposite of the actual case).

**Comment by rpgoldman** [comment]
Instead of looking at the signature string, I believe cl4p2 should look at `inspect.signature(function).parameters`.

Taking the `keys` of the `parameters` will give a list of parameter names.  Then if you look at the corresponding value, and then the `kind`, you will see that the kind for the variables of my function is:

    <_ParameterKind.KEYWORD_ONLY: 3>

...and that should be used to translate the arglist.

I don't see any comment explaining why a slash character should indicate that there are only positional arguments, but it's definitely not a good heuristic.

**Comment by digikar99** [comment]
I hope to get back about this later this month, this seems to require a bit of rewrite; until then, would `pycall` work for you (else I'll need to get back earlier)?

Thanks for spotting this!
